before:
  hooks:
    - go mod tidy
    - go get github.com/woodpecker-ci/togo
    - sh -c "cd web/; go generate ./..."
builds:
  - id: server
    main: ./cmd/drone-server
    binary: woodpecker-server
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm
      # - arm64
    ldflags:
      - -s -w
      - -X github.com/woodpecker-ci/woodpecker/version.Version={{.Version}}
      - -extldflags "-static"
  - id: agent
    main: ./cmd/drone-agent
    binary: woodpecker-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm
      # - arm64
    ldflags:
      - -s -w
      - -X github.com/woodpecker-ci/woodpecker/version.Version={{.Version}}
      - -extldflags "-static"
  - id: cli
    dir: ./cli/drone
    binary: woodpecker-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      # - arm
      # - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -extldflags "-static"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - id: server
    package_name: server
    builds:
      - server
    file_name_template: "{{ .ProjectName }}-{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    homepage: https://github.com/woodpecker-ci/woodpecker
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    meta: true
  - id: agent
    package_name: agent
    builds:
      - agent
    file_name_template: "{{ .ProjectName }}-{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    homepage: https://github.com/woodpecker-ci/woodpecker
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    meta: true
  - id: cli
    package_name: cli
    builds:
      - cli
    file_name_template: "{{ .ProjectName }}-{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    homepage: https://github.com/woodpecker-ci/woodpecker
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    meta: true
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.server
    image_templates:
      - "woodpeckerci/woodpecker-server:{{ .Version }}"
      - "woodpeckerci/woodpecker-server:latest"
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.server.alpine
    image_templates:
      - "woodpeckerci/woodpecker-server:{{ .Version }}-alpine"
      - "woodpeckerci/woodpecker-server:latest-alpine"
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.agent
    image_templates:
      - "woodpeckerci/woodpecker-agent:{{ .Version }}"
      - "woodpeckerci/woodpecker-agent:latest"
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.agent.alpine
    image_templates:
      - "woodpeckerci/woodpecker-agent:{{ .Version }}-alpine"
      - "woodpeckerci/woodpecker-agent:latest-alpine"
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.cli
    image_templates:
      - "woodpeckerci/woodpecker-cli:{{ .Version }}"
      - "woodpeckerci/woodpecker-cli:latest"
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.cli.alpine
    image_templates:
      - "woodpeckerci/woodpecker-cli:{{ .Version }}-alpine"
      - "woodpeckerci/woodpecker-cli:latest-alpine"
archives:
  - id: server
    builds:
    - server
    name_template: "{{ .ProjectName }}-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
  - id: agent
    builds:
    - agent
    name_template: "{{ .ProjectName }}-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
  - id: cli
    builds:
    - cli
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
