clone:
  git:
    image: plugins/git:next

pipeline:
  release:
    image: golang:1.10
    secrets: [github_token, docker_username, docker_password]
    commands:
      curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

depends_on:
  - test
