clone:
  git:
    image: plugins/git:next

pipeline:
  fetch:
    image: docker:git
    commands:
      - git fetch --tags
      - git status

  release:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    secrets: [github_token, docker_username, docker_password]
    commands:
      - goreleaser release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: tag

  release-snapshot:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    secrets: [github_token, docker_username, docker_password]
    commands:
      - goreleaser release --snapshot
      - docker image ls
      - docker tag woodpeckerci/woodpecker-cli:latest woodpeckerci/woodpecker-cli:next
      - docker push woodpeckerci/woodpecker-cli:next
      - docker tag woodpeckerci/woodpecker-server:latest woodpeckerci/woodpecker-server:next
      - docker push woodpeckerci/woodpecker-server:next
      - docker tag woodpeckerci/woodpecker-agent:latest woodpeckerci/woodpecker-agent:next
      - docker push woodpeckerci/woodpecker-agent:next
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: master

# depends_on:
#   - "woodpecker/.test"
