clone:
  git:
    image: plugins/git:next

pipeline:
  fetch:
    image: docker:git
    commands:
      - git fetch --tags
      - git status
    when:
      event: push
      branch: master

  prepare-release:
    image: node:14-alpine
    secrets: [github_token]
    commands:
      - apk add git
      - npm i semantic-release @semantic-release/exec
      - npx semantic-release --dry-run
    when:
      event: push
      branch: master

  prepare-build:
    image: golang:1.16
    commands:
      - export WOODPECKER_VERSION=$(cat ./woodpecker-version)
      - echo "Version $WOODPECKER_VERSION"
      - go mod tidy
      - go get github.com/woodpecker-ci/togo
      - cd web/
      - go generate ./...
    when:
      event: push
      branch: master

  build:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    commands:
      - export WOODPECKER_VERSION=$(cat ./woodpecker-version)
      - test "version-$WOODPECKER_VERSION" != "version-" || exit 0
      - export GORELEASER_CURRENT_TAG="$WOODPECKER_VERSION"
      - goreleaser release --skip-validate --rm-dist --skip-publish
    when:
      event: push
      branch: master

  # build-packages:
  #   image: golang:1.16
  #   commands:
  #     - export WOODPECKER_VERSION=$(cat ./woodpecker-version)
  #     - test "version-$WOODPECKER_VERSION" != "version-" || exit 0
  #     - go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
  #     - nfpm package --config ./nfpm.yml --target ./dist
  #   when:
  #     event: push
  #     branch: master

  # build-archives:
  #   image: alpine:3.14.1
  #   commands:
  #     # TODO
  #     - echo "Do some building ..."
  #   when:
  #     event: push
  #     branch: master

  build-docker-server:
    group: build-docker
    image: anbraten/kaniko:v1.6.0-debug
    secrets: [docker_username, docker_password]
    environment:
      - IMAGE_TYPE=server
    commands:
      - export WOODPECKER_VERSION=$(cat ./woodpecker-version)
      - test "$WOODPECKER_VERSION" -ne "" || exit 0 # skip if no version is found
      - .woodpecker/scripts/build-docker-image.sh
    when:
      event: push
      branch: master

  build-docker-agent:
    group: build-docker
    image: anbraten/kaniko:v1.6.0-debug
    secrets: [docker_username, docker_password]
    environment:
      - IMAGE_TYPE=agent
    commands:
      - export WOODPECKER_VERSION=$(cat ./woodpecker-version)
      - test "$WOODPECKER_VERSION" -ne "" || exit 0 # skip if no version is found
      - .woodpecker/scripts/build-docker-image.sh
    when:
      event: push
      branch: master

  build-docker-cli:
    group: build-docker
    image: anbraten/kaniko:v1.6.0-debug
    secrets: [docker_username, docker_password]
    environment:
      - IMAGE_TYPE=cli
    commands:
      - export WOODPECKER_VERSION=$(cat ./woodpecker-version)
      - test "$WOODPECKER_VERSION" -ne "" || exit 0 # skip if no version is found
      - .woodpecker/scripts/build-docker-image.sh
    when:
      event: push
      branch: master

  release:
    image: node:14-alpine
    secrets: [github_token]
    commands:
      - export WOODPECKER_VERSION=$(cat ./woodpecker-version)
      - echo "Version $WOODPECKER_VERSION"
      - apk add git
      # should already be installed by prepare-release
      - npm i semantic-release @semantic-release/exec
      - npx semantic-release
    when:
      event: push
      branch: master

# depends_on:
#   - "woodpecker/.test"
