clone:
  git:
    image: plugins/git:next

pipeline:
  fetch:
    image: docker:git
    commands:
      - git fetch --tags
      - git status

  release:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    secrets: [github_token, docker_username, docker_password]
    commands:
      - goreleaser release
    when:
      event: tag

  release-snapshot:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    secrets: [github_token, docker_username, docker_password]
    commands:
      - goreleaser release --snapshot
      # docker tag woodpeckerci/woodpecker-cli:... woodpeckerci/woodpecker-cli:latest
      # - docker push woodpeckerci/woodpecker-cli:latest
      # docker tag woodpeckerci/woodpecker-server:... woodpeckerci/woodpecker-server:latest
      # - docker push woodpeckerci/woodpecker-server:latest
      # docker tag woodpeckerci/woodpecker-agent:... woodpeckerci/woodpecker-agent:latest
      # - docker push woodpeckerci/woodpecker-agent:latest
    when:
      event: push
      branch: master

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

# depends_on:
#   - "woodpecker/.test"
