clone:
  git:
    image: plugins/git:next

pipeline:
  fetch:
    image: docker:git
    commands:
      - git fetch --tags
      - git status

  build:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    commands:
      - export GORELEASER_CURRENT_TAG=$DRONE_TAG
      - goreleaser release --skip-validate --rm-dist --skip-publish
    when:
      event: tag

  # build-docker-server:
  #   group: build-docker
  #   image: gcr.io/kaniko-project/executor:v1.6.0-debug
  #   secrets: [docker_username, docker_password]
  #   environment:
  #     - IMAGE_TYPE=server
  #   commands:
  #     - .woodpecker/scripts/build-docker-image.sh
  #   when:
  #     event: tag

  # build-docker-agent:
  #   group: build-docker
  #   image: gcr.io/kaniko-project/executor:v1.6.0-debug
  #   secrets: [docker_username, docker_password]
  #   environment:
  #     - IMAGE_TYPE=agent
  #   commands:
  #     - .woodpecker/scripts/build-docker-image.sh
  #   when:
  #     event: tag

  # build-docker-cli:
  #   group: build-docker
  #   image: gcr.io/kaniko-project/executor:v1.6.0-debug
  #   secrets: [docker_username, docker_password]
  #   environment:
  #     - IMAGE_TYPE=cli
  #   commands:
  #     - .woodpecker/scripts/build-docker-image.sh
  #   when:
  #     event: tag

  release:
    image: node:14-alpine
    secrets: [github_token]
    commands:
      - npx semantic-release
    when:
      event: [push, tag]

  # release-github:
  #   image: plugins/github-release
  #   secrets: [github_token]
  #   api_key: $GITHUB_TOKEN
  #   files:
  #     - dist/checksums.txt
  #     - dist/*.apk
  #     - dist/*.deb
  #     - dist/*.rpm
  #     - dist/*.tar.gz
  #   title: $DRONE_TAG
  #   note: CHANGELOG.md
  #   when:
  #     event: tag

# depends_on:
#   - "woodpecker/.test"
