clone:
  git:
    image: plugins/git:next

pipeline:
  release:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    secrets: [github_token, docker_username, docker_password]
    commands:
      - release
    when:
      event: [tag, push]
      branch: master

depends_on:
  - test
