clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  release:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    secrets: [github_token, docker_username, docker_password]
    commands:
      - goreleaser release
    when:
      event: tag

  release-snapshot:
    image: ghcr.io/goreleaser/goreleaser:v0.174.1
    secrets: [github_token, docker_username, docker_password]
    commands:
      - goreleaser release
    when:
      event: push
      # branch: master

# depends_on:
#   - "woodpecker/.test"
